In [1]:
# 1.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected
# Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
# 2. Write a NumPy program to find common values between two arrays. Expected Output:
# Array1: [ 0 10 20 40 60] Array2: [10, 30, 40] Common values between two arrays: [10 40]

import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

# mask = np.isin(array1, array2)
# common_values = array1[mask]
common_values = np.intersect1d(array1, array2)

print(f"Array1: {array1}")
print(f"Array2: {array2}")
print(f"Common values: {common_values}")

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values: [10 40]


In [3]:
# 3. Write a NumPy program to find the set difference between two arrays. The set difference
# will return sorted, distinct values in array1 that are not in array2. Expected Output: Array1: [ 0
# 10 20 40 60 80] Array2: [10, 30, 40, 50, 70, 90] Set difference between two arrays: [ 0 20 60 80]

import numpy as np

# Define the two arrays
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

# Find values in array1 that are NOT in array2
difference = np.setdiff1d(array1, array2)   # automatically sorted

# Returns True for elements NOT in array2
# mask = ~np.isin(array1, array2)
# difference_unsorted = array1[mask]

print(f"Array1: {array1}")
print(f"Array2: {array2}")
print(f"Set difference: {difference}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


In [4]:
# 4. Write a NumPy program to compare two arrays using NumPy.
# Array a: [1 2]
# Array b: [4 5]
# a > b [False False]
# a >= b [False False]
# a < b [ True True]
# a <= b [ True True]

import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

print(f"Array a: {a}")
print(f"Array b: {b}")

print(f"a > b  {a > b}")
print(f"a >= b {a >= b}")
print(f"a < b  {a < b}")
print(f"a <= b {a <= b}")

Array a: [1 2]
Array b: [4 5]
a > b  [False False]
a >= b [False False]
a < b  [ True  True]
a <= b [ True  True]


In [1]:
# 5.Multiply Array (3,4) Elements by 3
# Write a NumPy program to create an array of (3, 4) shapes, multiply every element value by 3
# and display the result array.
# Expected Output:
# Original array elements:
# [[ 0 1 2 3]
# [ 4 5 6 7]
# [ 8 9 10 11]]
# New array elements:
# [[ 0 3 6 9]
# [12 15 18 21]
# [24 27 30 33]]

import numpy as np

array = np.arange(12).reshape(3, 4)

new = array * 3

print("Original array elements:")
print(array)

print("\nNew array elements:")
print(new)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
